In [162]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages

In [163]:
# Load the data file
file_path = '/Users/lanahuyen/UCB Bootcamp/Project 1/Group_Project_1/Resources/merged_df.csv'
data = pd.read_csv(file_path)

# List of valid industries
valid_industries = [
    'Artificial intelligence', 'Auto & transportation', 'Consumer & retail', 'Cybersecurity', 'Data management & analytics',
    'E-commerce & direct-to-consumer', 'Edtech', 'Hardware', 'Health', 'Internet', 'Internet software & services',
    'Mobile & telecommunications', 'Other', 'Supply chain, logistics, & delivery', 'Travel'
]
data.head()

,Unnamed: 0,Company,2022_Valuation,2023_Valuation,2024_Valuation,Date Joined,Country,City,Industry,Select Investors
0,0,ByteDance,$140,$225,225.0,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,$127,$137,150.0,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,SHEIN,$100,$66,66.0,7/3/2018,China,Shenzhen,E-commerce & direct-to-consumer,"Tiger Global Management, Sequoia Capital China..."
3,3,Stripe,$95,$50,65.0,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
4,4,Canva,$40,$40,25.4,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."

In [164]:
# Clean the data
cleaned_data = data[
    (data['Industry'].isin(valid_industries)) &
    (data[['2022_Valuation', '2023_Valuation', '2024_Valuation']].notnull().all(axis=1))
]

# Convert valuation columns to numeric values (removing any non-numeric characters)
cleaned_data['2022_Valuation'] = cleaned_data['2022_Valuation'].replace({'\$': '', ',': ''}, regex=True).astype(float)
cleaned_data['2023_Valuation'] = cleaned_data['2023_Valuation'].replace({'\$': '', ',': ''}, regex=True).astype(float)
cleaned_data['2024_Valuation'] = cleaned_data['2024_Valuation'].replace({'\$': '', ',': ''}, regex=True).astype(float)

cleaned_data.head()

/var/folders/6p/h0sr07r51_qcbxx4mdpg2cc80000gn/T/ipykernel_33802/3777406106.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['2022_Valuation'] = cleaned_data['2022_Valuation'].replace({'\$': '', ',': ''}, regex=True).astype(float)
/var/folders/6p/h0sr07r51_qcbxx4mdpg2cc80000gn/T/ipykernel_33802/3777406106.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['2023_Valuation'] = cleaned_data['2023_Valuation'].replace({'\$': '', ',': ''}, regex=True).astype(float)
/var/folders/6p/h0sr07r51_qcbxx4mdpg2cc80000gn/T/ipykernel_33802/3777406106.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['2024_Valuation'] = cleaned_data['2024_Valuation'].replace({'\$': '', ',': ''}, regex=True).astype(float)

,Unnamed: 0,Company,2022_Valuation,2023_Valuation,2024_Valuation,Date Joined,Country,City,Industry,Select Investors
0,0,ByteDance,140.0,225.0,225.0,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,127.0,137.0,150.0,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,SHEIN,100.0,66.0,66.0,7/3/2018,China,Shenzhen,E-commerce & direct-to-consumer,"Tiger Global Management, Sequoia Capital China..."
4,4,Canva,40.0,40.0,25.4,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."
7,7,Databricks,38.0,31.0,43.0,2/5/2019,United States,San Francisco,Data management & analytics,"Andreessen Horowitz, New Enterprise Associates..."

In [165]:
# Calculate growth columns
cleaned_data['22 Growth'] = ((cleaned_data['2023_Valuation'] - cleaned_data['2022_Valuation']) / cleaned_data['2022_Valuation']) * 100
cleaned_data['23 Growth'] = ((cleaned_data['2024_Valuation'] - cleaned_data['2023_Valuation']) / cleaned_data['2023_Valuation']) * 100
cleaned_data['Total Growth'] = ((cleaned_data['2024_Valuation'] - cleaned_data['2022_Valuation']) / cleaned_data['2022_Valuation']) * 100

/var/folders/6p/h0sr07r51_qcbxx4mdpg2cc80000gn/T/ipykernel_33802/127568932.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['22 Growth'] = ((cleaned_data['2023_Valuation'] - cleaned_data['2022_Valuation']) / cleaned_data['2022_Valuation']) * 100
/var/folders/6p/h0sr07r51_qcbxx4mdpg2cc80000gn/T/ipykernel_33802/127568932.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['23 Growth'] = ((cleaned_data['2024_Valuation'] - cleaned_data['2023_Valuation']) / cleaned_data['2023_Valuation']) * 100
/var/folders/6p/h0sr07r51_qcbxx4mdpg2cc80000gn/T/ipykernel_33802/127568932.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['Total Growth'] = ((cleaned_data['2024_Valuation'] - cleaned_data['2022_Valuation']) / cleaned_data['2022_Valuation']) * 100

In [166]:
# Statistical analysis
# Group by Industry and calculate mean and median growth rates
industry_growth_stats = cleaned_data.groupby('Industry').agg({
    '22 Growth': ['mean', 'median'],
    '23 Growth': ['mean', 'median'],
    'Total Growth': ['mean', 'median']
}).reset_index()

# Flatten the multi-level columns
industry_growth_stats.columns = [' '.join(col).strip() for col in industry_growth_stats.columns.values]


# Set the style for the plots
sns.set(style="whitegrid")

In [167]:
# Create a PDF file to save all the plots
with PdfPages('/Users/lanahuyen/UCB Bootcamp/Project 1/Group_Project_1/industry_growth_analysis.pdf') as pdf:

    plt.figure(figsize=(23, 8))
    sns.boxplot(x='22 Growth', y='Industry', data=cleaned_data)
    plt.title('Industry vs 2022 Growth', fontsize=20, fontweight='bold')
    plt.xlabel('22 Growth (%)')
    plt.ylabel('Industry')
    plt.xlim(-100, 150)
    pdf.savefig()
    plt.close()

    # Industry vs 23 Growth Boxplot
    plt.figure(figsize=(23, 8))
    sns.boxplot(x='23 Growth', y='Industry', data=cleaned_data)
    plt.title('Industry vs 2023 Growth', fontsize=20, fontweight='bold')
    plt.xlabel('23 Growth (%)')
    plt.ylabel('Industry')
    plt.xlim(-100, 150)
    pdf.savefig()
    plt.close()

    # Industry vs Total Growth Boxplot
    plt.figure(figsize=(23, 8))
    sns.boxplot(x='Total Growth', y='Industry', data=cleaned_data)
    plt.title('Industry vs Total Growth', fontsize=20, fontweight='bold')
    plt.xlabel('Total Growth (%)')
    plt.ylabel('Industry')
    plt.xlim(-100, 150)
    pdf.savefig()
    plt.close()


    # Bar graph for average 22 Growth per industry
    plt.figure(figsize=(23, 8))
    sns.barplot(x='22 Growth mean', y='Industry', data=industry_growth_stats)
    plt.title('Average 2022 Growth per Industry', fontsize=20, fontweight='bold')
    plt.xlabel('Average 22 Growth (%)')
    plt.ylabel('Industry')
    pdf.savefig()
    plt.close()

    # Bar graph for average 23 Growth per industry
    plt.figure(figsize=(23, 8))
    sns.barplot(x='23 Growth mean', y='Industry', data=industry_growth_stats)
    plt.title('Average 2023 Growth per Industry', fontsize=20, fontweight='bold')
    plt.xlabel('Average 23 Growth (%)')
    plt.ylabel('Industry')
    pdf.savefig()
    plt.close()

    # Bar graph for average Total Growth per industry
    plt.figure(figsize=(23, 8))
    sns.barplot(x='Total Growth mean', y='Industry', data=industry_growth_stats)
    plt.title('Average Total Growth per Industry', fontsize=20, fontweight='bold')
    plt.xlabel('Average Total Growth (%)')
    plt.ylabel('Industry')
    pdf.savefig()
    plt.close()